Cars model
AntonMaxen/Databas01 pull request #2
Opened 2020-11-10 11:48 UTC by marcusjohnsson

Cars Model - "Kunde inte låta bli att testa arbetsflödet...  =D"

2020-11-11 11:37 UTC, ewardsoberg commented
Lookin good. 
Ser dock två filer i PR:en, en Car Models som är tom på kod. Och den Car Model - Test.
Men koden i Car Model - Test ser bra ut :) !

2020-11-12 08:54 UTC, AntonMaxen commented on app/models/cars.py
> +    @property
@property not needed

2020-11-12 08:56 UTC, marcusjohnsson commented on app/models/cars.py
> +    @property
Check! Jag fixar det!

2020-11-12 08:57 UTC, ewardsoberg commented on app/models/cars.py
> +    @property
(nullable=False) = Not Null

2020-11-12 09:08 UTC, marcusjohnsson commented on app/models/cars.py
> +    license_number = sa.Column(sa.Integer, primary_key=True)
eyryee

2020-11-12 09:12 UTC, ewardsoberg requested changes

2020-11-12 09:12 UTC, ewardsoberg commented on app/models/cars.py
> +    brand_name = sa.Column(sa.String(45))
lägg till nullable(not null), exempel,  brand_name = sa.Column(sa.String(45), nullable=False)

2020-11-12 09:22 UTC, ewardsoberg approved these changes

2020-11-12 09:23 UTC, merged